"""empty message

Revision ID: 4e5b28d69910
Revises: ea35e07707f4
Create Date: 2024-02-13 14:12:30.745642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5b28d69910'
down_revision = 'ea35e07707f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('date', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'date')
    # ### end Alembic commands ###
